# This is a basic workflow to help you get started with Actions
name: Deploy AKS Lab Services Only

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch

on:  
  workflow_dispatch:
    inputs:
      workflowAction:
        description: 'Action'
        default: 'Deploy AKS Lab Services Only'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - name: Install IstioCtl
        run: |-
          # Specify the Istio version that will be leveraged throughout these instructions
          ISTIO_VERSION=1.7.3

          curl -sL "https://github.com/istio/istio/releases/download/$ISTIO_VERSION/istioctl-$ISTIO_VERSION-linux-amd64.tar.gz" | tar xz
          
          sudo mv ./istioctl /usr/local/bin/istioctl
          sudo chmod +x /usr/local/bin/istioctl

      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          # Set this value to true to enable Azure PowerShell Login in addition to Az CLI login
          enable-AzPSSession: true # optional
          
      - name: Azure PowerShell - Deploy All Microservices
        uses: Azure/powershell@v1
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          # Specify the Az PowerShell script here.
          inlineScript: |          
            ./ps1/workflow/azure-aks-lab-cicd.ps1 -DeployServices
          # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
          azPSVersion: 4.7.0
          # Select the value of the ErrorActionPreference variable for executing the script. Options: stop, continue, silentlyContinue. Default is Stop.
          errorActionPreference: silentlyContinue # optional, default is Stop
          # If this is true, this task will fail if any errors are written to the error pipeline, or if any data is written to the Standard Error stream.
          failOnStandardError: false # optional, default is false
